return {
	Player = {
		MaxHealth = 100,
		WalkSpeed = 18,
		SprintSpeed = 26,
		CrouchSpeed = 8,
		JumpPower = 50,
		CameraMinZoomDistance = 0.5,
		CameraMaxZoomDistance = 20,
		StartingAmmo = 30,
		StartingMaterials = 3,
	},
	Weapon = {
		Damage = 34,
		Range = 350,
		FireDelay = 0.18,
	},
	Zombie = {
		MaxActive = 40,
		Health = 100,
		WalkSpeed = 9,
		NightSpeed = 14,
		Damage = 10,
		AttackDistance = 5,
		AttackDelay = 0.8,
		SpawnDelay = 2.7,
	},
	Cycle = {
		DaySeconds = 70,
		NightSeconds = 55,
	},
	Barricade = {
		Cost = 2,
		MaxDistance = 14,
	},
}
